version: build{build}

branches:
  only:
  - master

environment:
  NSpectatorVersion: 0.9.5
  NSpectatorPackageVersion: "0.9.5-ci$(APPVEYOR_BUILD_NUMBER)"
  
cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: "$(NSpectatorVersion)"
  assembly_file_version: "$(NSpectatorVersion)"
  assembly_informational_version: "$(NSpectatorPackageVersion)"

nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Debug

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore

build:
  project: NSpectator.sln
  verbosity: normal

test:
  assemblies:
  - NSpectator.Specs.dll

artifacts:
 - path: src\NSpectator\bin\Debug\NSpectator.dll